### ISSUE TITLE
Support .babelrc.js files

### ISSUE THREAD

**Issue by novemberborn** [novemberborn/hullabaloo-config-manager#4]
Babel 7.0 [adds support for `.babelrc.js` files](https://github.com/babel/babel/pull/4892). We need to follow suit.

* When looking for `babelrc`, prioritize `.babelrc.js` over reading `"babel"` from `package.json`
* Include a hash for the `.babelrc.js` source in the source hashes and cache keys
* When verifying hashes for the current environment, if there is a `babelrcDir`, and `.babelrc` is not one of the sources, and neither is `.babelrc.js`, ensure `.babelrc.js` is still missing

Since the output of `.babelrc.js` files can vary, we cannot recurse through it when collecting configs. Instead we need to terminate the chain at the `.babelrc.js` file and communicate its existence to consuming code. That code then needs to call a different routine which can then resolve the config and build a fuller chain, fit for the current environment. Ideally this chain can then be hashed again to utilize caches, and serialized if necessary.

Of course the `.babelrc.js` file may return function references for plugins and presets, and option values for plugins / presets which cannot be serialized. This needs to be detected so the consuming code can use the earlier, incomplete chain, as its Babel config.

When loading the `.babelrc.js` file keep in mind that it [should support faux-ES-modules](https://github.com/babel/babel/pull/4892/files#diff-a34f5b8fdec115a91b67158c86404e1bR129). It might also be good to load it in a different context without access to the current `require` cache or non-standard globals. This to discourage "clever" hacks that are then foiled by the resulting config being cached by consuming code.

**Comment by loganfsmyth** [comment]
One note I'll add here is that `.babelrc.js` files can also export a function, and that function has an API that gets passed to it for users to manage cache invalidation related to thing like the environment variables and any other globals their config might rely on. The expectation is that if the environment variables change, the exported function would be re-executed. I assume you'll want to error in that case?

**Comment by novemberborn** [comment]
It's been a long time since I opened this issue, so I'll have to look at what's in Babel 7 now. My hunch is that all configurations should work, and we'll have to document the circumstances in which the cache keys computed by this package are unreliable.
